# Generated by Django 5.1.4 on 2025-01-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=7)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('DOB', models.DateField()),
                ('Skill', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=30)),
            ],
        ),
    ]
