# Generated by Django 5.1.4 on 2025-07-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobannouncement',
            name='profession',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('doctor', 'Doctor'), ('engineer', 'Engineer'), ('labor', 'Labor'), ('driver', 'Driver'), ('jyami', 'Jyami'), ('mistri', 'Mistri'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('painter', 'Painter'), ('mason', 'Mason'), ('mechanic', 'Mechanic'), ('welder', 'Welder'), ('carpenter', 'Carpenter'), ('tailor', 'Tailor'), ('agricultural_worker', 'Agricultural Worker'), ('construction_worker', 'Construction Worker'), ('porter', 'Porter'), ('cleaner', 'Cleaner'), ('waiter', 'Waiter'), ('cook', 'Cook'), ('security_guard', 'Security Guard'), ('delivery_person', 'Delivery Person'), ('shop_assistant', 'Shop Assistant'), ('street_vendor', 'Street Vendor'), ('butcher', 'Butcher'), ('fisherman', 'Fisherman'), ('rickshaw_driver', 'Rickshaw Driver'), ('barber', 'Barber'), ('fruit_seller', 'Fruit Seller'), ('taxi_driver', 'Taxi Driver'), ('auto_rickshaw_driver', 'Auto Rickshaw Driver'), ('garbage_collector', 'Garbage Collector'), ('other', 'Other')], max_length=50, null=True, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='professional_skill',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('doctor', 'Doctor'), ('engineer', 'Engineer'), ('labor', 'Labor'), ('driver', 'Driver'), ('jyami', 'Jyami'), ('mistri', 'Mistri'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('painter', 'Painter'), ('mason', 'Mason'), ('mechanic', 'Mechanic'), ('welder', 'Welder'), ('carpenter', 'Carpenter'), ('tailor', 'Tailor'), ('agricultural_worker', 'Agricultural Worker'), ('construction_worker', 'Construction Worker'), ('porter', 'Porter'), ('cleaner', 'Cleaner'), ('waiter', 'Waiter'), ('cook', 'Cook'), ('security_guard', 'Security Guard'), ('delivery_person', 'Delivery Person'), ('shop_assistant', 'Shop Assistant'), ('street_vendor', 'Street Vendor'), ('butcher', 'Butcher'), ('fisherman', 'Fisherman'), ('rickshaw_driver', 'Rickshaw Driver'), ('barber', 'Barber'), ('fruit_seller', 'Fruit Seller'), ('taxi_driver', 'Taxi Driver'), ('auto_rickshaw_driver', 'Auto Rickshaw Driver'), ('garbage_collector', 'Garbage Collector'), ('other', 'Other')], max_length=50, verbose_name='Professional Skill'),
        ),
    ]
