# Generated by Django 5.1.4 on 2025-01-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('national_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10)),
                ('citizenship_number', models.CharField(max_length=50)),
                ('citizenship_issued_date', models.DateField()),
                ('citizenship_issued_district', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('spouse_name', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_province', models.CharField(max_length=100)),
                ('permanent_district', models.CharField(max_length=100)),
                ('permanent_municipality', models.CharField(max_length=100)),
                ('permanent_ward_no', models.PositiveIntegerField()),
                ('permanent_tole_name', models.CharField(max_length=100)),
                ('current_province', models.CharField(max_length=100)),
                ('current_district', models.CharField(max_length=100)),
                ('current_municipality', models.CharField(max_length=100)),
                ('current_ward_no', models.PositiveIntegerField()),
                ('current_tole_name', models.CharField(max_length=100)),
                ('education_background', models.CharField(choices=[('slc_see', 'SLC/SEE'), ('plus_two', '+2'), ('bachelor', 'Bachelor'), ('masters', 'Masters'), ('diploma', 'Diploma')], max_length=20)),
                ('professional_skill', models.TextField()),
                ('photo_pp', models.ImageField(upload_to='uploads/photos/')),
                ('citizenship_photo_front', models.ImageField(upload_to='uploads/citizenship/')),
                ('citizenship_photo_back', models.ImageField(upload_to='uploads/citizenship/')),
                ('cv_resume', models.FileField(upload_to='uploads/resumes/')),
            ],
        ),
    ]
