# Generated by Django 5.1.4 on 2025-01-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_personaldetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='current_district',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='current_municipality',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='current_province',
            new_name='province',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='current_tole_name',
            new_name='tole_name',
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='current_ward_no',
            new_name='ward_no',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='permanent_district',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='permanent_municipality',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='permanent_province',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='permanent_tole_name',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='permanent_ward_no',
        ),
    ]
