# Generated by Django 5.1.4 on 2025-01-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_current_district_personaldetails_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('compoleted', 'COMPLETED')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
