# Generated by Django 5.1.4 on 2025-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_personaldetails_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='citizenship_issued_date',
            field=models.DateField(verbose_name='Citizenship Issued Date'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='citizenship_issued_district',
            field=models.CharField(max_length=100, verbose_name='Citizenship Issued District'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='citizenship_number',
            field=models.CharField(max_length=50, verbose_name='Citizenship Number'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='citizenship_photo_back',
            field=models.ImageField(upload_to='uploads/citizenship/', verbose_name='Citizenship Photo (Back)'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='citizenship_photo_front',
            field=models.ImageField(upload_to='uploads/citizenship/', verbose_name='Citizenship Photo (Front)'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='contact_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='cv_resume',
            field=models.FileField(upload_to='uploads/resumes/', verbose_name='Resume/CV'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='district',
            field=models.CharField(max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='dob',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='education_background',
            field=models.CharField(choices=[('slc_see', 'SLC/SEE'), ('plus_two', '+2'), ('bachelor', 'Bachelor'), ('masters', 'Masters'), ('diploma', 'Diploma'), ('uneducated', 'Uneducated'), ('class_eight_pass', 'Class 8 pass'), ('class_five_pass', 'Class 5 pass')], max_length=20, verbose_name='Education Background'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='fathers_name',
            field=models.CharField(max_length=100, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='mobile_number',
            field=models.CharField(max_length=10, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='mothers_name',
            field=models.CharField(max_length=100, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='municipality',
            field=models.CharField(max_length=100, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='National ID Number'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='photo_pp',
            field=models.ImageField(upload_to='uploads/photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='professional_skill',
            field=models.TextField(verbose_name='Professional Skill'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='province',
            field=models.CharField(max_length=100, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spouse Name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='tole_name',
            field=models.CharField(max_length=100, verbose_name='Tole Name'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='ward_no',
            field=models.PositiveIntegerField(verbose_name='Ward No'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Address',
            field=models.CharField(max_length=30, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='DOB',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Gender',
            field=models.CharField(max_length=7, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='PhoneNumber',
            field=models.CharField(max_length=12, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Skill',
            field=models.CharField(max_length=25, verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
