# Generated by Django 5.1.4 on 2025-01-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_professions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed')], default='pending', max_length=20, null=True),
        ),
    ]
