# Generated by Django 5.1.4 on 2025-01-22 17:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_personaldetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='citizenship_photo_back',
            field=models.ImageField(upload_to='uploads/citizenship/', validators=[app.models.validate_citizenship_photo], verbose_name='Citizenship Photo (Back)'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='citizenship_photo_front',
            field=models.ImageField(upload_to='uploads/citizenship/', validators=[app.models.validate_citizenship_photo], verbose_name='Citizenship Photo (Front)'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='cv_resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/resumes/', validators=[app.models.validate_cv_resume], verbose_name='Resume/CV'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='photo_pp',
            field=models.ImageField(upload_to='uploads/photos/', validators=[app.models.validate_photo_pp], verbose_name='Profile Photo'),
        ),
    ]
