# Generated by Django 5.1.4 on 2025-01-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_personaldetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='education_background',
            field=models.CharField(choices=[('slc_see', 'SLC/SEE'), ('plus_two', '+2'), ('bachelor', 'Bachelor'), ('masters', 'Masters'), ('diploma', 'Diploma'), ('phd', 'PHD'), ('uneducated', 'Uneducated'), ('class_eight_pass', 'Class 8 pass'), ('class_five_pass', 'Class 5 pass')], max_length=20, verbose_name='Education Background'),
        ),
    ]
