# Generated by Django 5.1.4 on 2025-01-23 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_personaldetails_citizenship_photo_back_and_more'),
        ('app', '0008_alter_personaldetails_education_background'),
    ]

    operations = [
    ]
