# Generated by Django 5.1.4 on 2025-03-31 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20250123_0927'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='employment_status',
            field=models.CharField(choices=[('occupied', 'Occupied'), ('unoccupied', 'Unoccupied')], default='unoccupied', max_length=20, verbose_name='Employment Status'),
        ),
        migrations.CreateModel(
            name='JobAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='Posted Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('required_personnel', models.PositiveIntegerField(default=1, verbose_name='Required Personnel')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.professions', verbose_name='Profession')),
            ],
        ),
    ]
